meta_product_name: "LynxAM"
meta_title: "LynxAM - L'IA au service du cash"
meta_description: "AI powered tool to optimize professional real estate management"
meta_image: "lynx.png"
twitter_account: "@LynxAM"
